name: Linux Build and Test

on: [push, pull_request]

jobs:
  Installation:
    name: Installation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: installing preliminaries
      run: pip3 install -e .
    - name: simba init
      run: simba init
